// Code generated by stanc v2.34.0
#include <stan/model/model_header.hpp>
namespace bivar_logistic_angular_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 28> locations_array__ =
  {" (found before start of program)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 41, column 2 to column 29)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 45, column 2 to column 33)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 49, column 2 to column 22)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 52, column 4 to column 46)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 51, column 17 to line 53, column 3)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 51, column 2 to line 53, column 3)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 29, column 2 to column 17)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 30, column 2 to column 17)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 31, column 8 to column 9)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 31, column 2 to column 37)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 3, column 4, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 2, column 47, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 8, column 4, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 9, column 4, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 7, column 50, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 14, column 4, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 15, column 4, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 13, column 49, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 20, column 4, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 21, column 4, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 19, column 50, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 26, column 4, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 25, column 67, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 31, column 4, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/gauge_fcns_euc.stanfunctions', line 30, column 53, included from\n'stan/angular/bivar_logistic_angular.stan', line 2, column 2)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 24, column 8 to column 94)",
  " (in 'stan/angular/bivar_logistic_angular.stan', line 23, column 67 to line 25, column 3)"};
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
gauss_gauge(const T0__& x1, const T1__& x2, const T2__& rho, std::ostream*
            pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
logistic_gauge(const T0__& x1, const T1__& x2, const T2__& dep, std::ostream*
               pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
inv_log_gauge(const T0__& x1, const T1__& x2, const T2__& dep, std::ostream*
              pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
asym_log_gauge(const T0__& x1, const T1__& x2, const T2__& dep, std::ostream*
               pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
dirichlet_gauge(const T0__& x1, const T1__& x2, const T2__& theta1,
                const T3__& theta2, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
rectangular_gauge(const T0__& x1, const T1__& x2, const T2__& dep,
                  std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              std::is_integral<T2__>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T3__>
angular_lpdf(const T0__& angle, const T1__& pars, const T2__& dim,
             const T3__& L_volume, std::ostream* pstream__);
// real gauss_gauge(real, real, real)
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>*>
stan::promote_args_t<T0__, T1__, T2__>
gauss_gauge(const T0__& x1, const T1__& x2, const T2__& rho, std::ostream*
            pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 11;
    return (((x1 + x2) - ((2 * rho) * stan::math::sqrt((x1 * x2)))) / (1 -
           stan::math::pow(rho, 2)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real logistic_gauge(real, real, real)
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>*>
stan::promote_args_t<T0__, T1__, T2__>
logistic_gauge(const T0__& x1, const T1__& x2, const T2__& dep, std::ostream*
               pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 13;
    dep_inv = (1 / dep);
    current_statement__ = 14;
    return ((dep_inv * stan::math::fmax(x1, x2)) + ((1 - dep_inv) *
           stan::math::fmin(x1, x2)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real inv_log_gauge(real, real, real)
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>*>
stan::promote_args_t<T0__, T1__, T2__>
inv_log_gauge(const T0__& x1, const T1__& x2, const T2__& dep, std::ostream*
              pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 16;
    dep_inv = (1 / dep);
    current_statement__ = 17;
    return stan::math::pow((stan::math::pow(x1, dep_inv) +
             stan::math::pow(x2, dep_inv)), dep);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real asym_log_gauge(real, real, real)
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>*>
stan::promote_args_t<T0__, T1__, T2__>
asym_log_gauge(const T0__& x1, const T1__& x2, const T2__& dep, std::ostream*
               pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 19;
    dep_inv = (1 / dep);
    current_statement__ = 20;
    return stan::math::fmin((x1 + x2), ((dep_inv * stan::math::fmax(x1, x2))
             + ((1 - dep_inv) * stan::math::fmin(x1, x2))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real dirichlet_gauge(real, real, real, real)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
dirichlet_gauge(const T0__& x1, const T1__& x2, const T2__& theta1,
                const T3__& theta2, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 22;
    return (((((1 + theta1) + theta2) * stan::math::fmax(x1, x2)) - (theta1 *
           x1)) - (theta2 * x2));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real rectangular_gauge(real, real, real)
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>*>
stan::promote_args_t<T0__, T1__, T2__>
rectangular_gauge(const T0__& x1, const T1__& x2, const T2__& dep,
                  std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 24;
    return stan::math::fmax(
             stan::math::fmax(((x1 - x2) / dep), ((x2 - x1) / dep)), ((x1 +
             x2) / (2 - dep)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real angular_lpdf(real, real, int, real)
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              std::is_integral<T2__>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T3__>
angular_lpdf(const T0__& angle, const T1__& pars, const T2__& dim,
             const T3__& L_volume, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 26;
    return (((-(dim) *
           stan::math::log(
             logistic_gauge(angle, (1 - angle), pars, pstream__)))
           - stan::math::log(dim)) - stan::math::log(L_volume));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class bivar_logistic_angular_model final : public model_base_crtp<bivar_logistic_angular_model> {
 private:
  int N;
  int d;
  std::vector<double> w1;
 public:
  ~bivar_logistic_angular_model() {}
  bivar_logistic_angular_model(stan::io::var_context& context__, unsigned int
                               random_seed__ = 0, std::ostream*
                               pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "bivar_logistic_angular_model_namespace::bivar_logistic_angular_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 7;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 7;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 8;
      context__.validate_dims("data initialization", "d", "int",
        std::vector<size_t>{});
      d = std::numeric_limits<int>::min();
      current_statement__ = 8;
      d = context__.vals_i("d")[(1 - 1)];
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "d", d, 1);
      current_statement__ = 9;
      stan::math::validate_non_negative_index("w1", "N", N);
      current_statement__ = 10;
      context__.validate_dims("data initialization", "w1", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      w1 = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 10;
      w1 = context__.vals_r("w1");
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "w1", w1, 0);
      current_statement__ = 10;
      stan::math::check_less_or_equal(function__, "w1", w1, 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1;
  }
  inline std::string model_name() const final {
    return "bivar_logistic_angular_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.34.0",
             "stancflags = --include-paths=stan/angular"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_logistic_angular_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 1;
      dep = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      local_scalar_t__ L = DUMMY_VAR__;
      current_statement__ = 2;
      L = dep;
      current_statement__ = 2;
      stan::math::check_greater_or_equal(function__, "L", L, 0);
      current_statement__ = 2;
      stan::math::check_less_or_equal(function__, "L", L, 1);
      {
        current_statement__ = 3;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(dep, 0, 1));
        current_statement__ = 6;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 4;
          lp_accum__.add(angular_lpdf<false>(
                           stan::model::rvalue(w1, "w1",
                             stan::model::index_uni(n)), dep, d, L, pstream__));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_logistic_angular_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 1;
      dep = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      local_scalar_t__ L = DUMMY_VAR__;
      current_statement__ = 2;
      L = dep;
      current_statement__ = 2;
      stan::math::check_greater_or_equal(function__, "L", L, 0);
      current_statement__ = 2;
      stan::math::check_less_or_equal(function__, "L", L, 1);
      {
        current_statement__ = 3;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(dep, 0, 1));
        current_statement__ = 6;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 4;
          lp_accum__.add(angular_lpdf<false>(
                           stan::model::rvalue(w1, "w1",
                             stan::model::index_uni(n)), dep, d, L, pstream__));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "bivar_logistic_angular_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double dep = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      dep = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      double L = std::numeric_limits<double>::quiet_NaN();
      out__.write(dep);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 2;
      L = dep;
      current_statement__ = 2;
      stan::math::check_greater_or_equal(function__, "L", L, 0);
      current_statement__ = 2;
      stan::math::check_less_or_equal(function__, "L", L, 1);
      if (emit_transformed_parameters__) {
        out__.write(L);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 1;
      dep = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, dep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "dep", "double",
        std::vector<size_t>{});
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 1;
      dep = context__.vals_r("dep")[(1 - 1)];
      out__.write_free_lub(0, 1, dep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"dep"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"L"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "dep");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "L");
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "dep");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "L");
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"dep\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"dep\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1;
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = 1;
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = bivar_logistic_angular_model_namespace::bivar_logistic_angular_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return bivar_logistic_angular_model_namespace::profiles__;
}
#endif