// Code generated by stanc v2.34.0
#include <stan/model/model_header.hpp>
namespace bivar_gauss_angular_bern_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 19> locations_array__ =
  {" (found before start of program)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 11, column 2 to column 21)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 15, column 9 to column 10)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 15, column 2 to column 39)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 17, column 11 to column 12)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 17, column 4 to column 32)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 19, column 6 to column 21)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 20, column 6 to column 28)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 21, column 6 to column 47)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 18, column 19 to line 22, column 5)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 18, column 4 to line 22, column 5)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 23, column 4 to column 31)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 16, column 17 to line 24, column 3)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 16, column 2 to line 24, column 3)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 2, column 2 to column 17)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 3, column 8 to column 9)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 3, column 2 to column 37)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 7, column 2 to column 13)",
  " (in 'stan/angular/bivar_gauss_angular_bern.stan', line 11, column 10 to column 11)"};
class bivar_gauss_angular_bern_model final : public model_base_crtp<bivar_gauss_angular_bern_model> {
 private:
  int N;
  std::vector<double> w1;
  int K;
 public:
  ~bivar_gauss_angular_bern_model() {}
  bivar_gauss_angular_bern_model(stan::io::var_context& context__,
                                 unsigned int random_seed__ = 0,
                                 std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "bivar_gauss_angular_bern_model_namespace::bivar_gauss_angular_bern_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 14;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 14;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 15;
      stan::math::validate_non_negative_index("w1", "N", N);
      current_statement__ = 16;
      context__.validate_dims("data initialization", "w1", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      w1 = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 16;
      w1 = context__.vals_r("w1");
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "w1", w1, 0);
      current_statement__ = 16;
      stan::math::check_less_or_equal(function__, "w1", w1, 1);
      current_statement__ = 17;
      K = std::numeric_limits<int>::min();
      current_statement__ = 17;
      K = 10;
      current_statement__ = 18;
      stan::math::validate_positive_index("weights", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (K - 1);
  }
  inline std::string model_name() const final {
    return "bivar_gauss_angular_bern_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.34.0",
             "stancflags = --include-paths=stan/angular"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_gauss_angular_bern_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> weights =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      weights = in__.template read_constrain_simplex<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      {
        current_statement__ = 2;
        stan::math::validate_non_negative_index("log_weights", "K", K);
        Eigen::Matrix<local_scalar_t__,-1,1> log_weights =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
        current_statement__ = 3;
        stan::model::assign(log_weights, stan::math::log(weights),
          "assigning variable log_weights");
        current_statement__ = 13;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 4;
          stan::math::validate_non_negative_index("lps", "K", K);
          Eigen::Matrix<local_scalar_t__,-1,1> lps =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
          current_statement__ = 5;
          stan::model::assign(lps, log_weights, "assigning variable lps");
          current_statement__ = 10;
          for (int j = 1; j <= K; ++j) {
            local_scalar_t__ alpha = DUMMY_VAR__;
            current_statement__ = 6;
            alpha = j;
            local_scalar_t__ beta = DUMMY_VAR__;
            current_statement__ = 7;
            beta = ((K - j) + 1);
            current_statement__ = 8;
            stan::model::assign(lps,
              (stan::model::rvalue(lps, "lps", stan::model::index_uni(j)) +
              stan::math::beta_lpdf<false>(
                stan::model::rvalue(w1, "w1", stan::model::index_uni(n)),
                alpha, beta)), "assigning variable lps",
              stan::model::index_uni(j));
          }
          current_statement__ = 11;
          lp_accum__.add(stan::math::log_sum_exp(lps));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_gauss_angular_bern_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> weights =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      weights = in__.template read_constrain_simplex<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      {
        current_statement__ = 2;
        stan::math::validate_non_negative_index("log_weights", "K", K);
        Eigen::Matrix<local_scalar_t__,-1,1> log_weights =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
        current_statement__ = 3;
        stan::model::assign(log_weights, stan::math::log(weights),
          "assigning variable log_weights");
        current_statement__ = 13;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 4;
          stan::math::validate_non_negative_index("lps", "K", K);
          Eigen::Matrix<local_scalar_t__,-1,1> lps =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
          current_statement__ = 5;
          stan::model::assign(lps, log_weights, "assigning variable lps");
          current_statement__ = 10;
          for (int j = 1; j <= K; ++j) {
            local_scalar_t__ alpha = DUMMY_VAR__;
            current_statement__ = 6;
            alpha = j;
            local_scalar_t__ beta = DUMMY_VAR__;
            current_statement__ = 7;
            beta = ((K - j) + 1);
            current_statement__ = 8;
            stan::model::assign(lps,
              (stan::model::rvalue(lps, "lps", stan::model::index_uni(j)) +
              stan::math::beta_lpdf<false>(
                stan::model::rvalue(w1, "w1", stan::model::index_uni(n)),
                alpha, beta)), "assigning variable lps",
              stan::model::index_uni(j));
          }
          current_statement__ = 11;
          lp_accum__.add(stan::math::log_sum_exp(lps));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "bivar_gauss_angular_bern_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> weights =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      weights = in__.template read_constrain_simplex<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      out__.write(weights);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> weights =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(weights,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable weights");
      out__.write_free_simplex(weights);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "weights",
        "double", std::vector<size_t>{static_cast<size_t>(K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> weights =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> weights_flat__;
        current_statement__ = 1;
        weights_flat__ = context__.vals_r("weights");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          stan::model::assign(weights, weights_flat__[(pos__ - 1)],
            "assigning variable weights", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(weights);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"weights"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K)}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "weights" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "weights" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"weights\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"weights\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((K -1)) + "},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = K;
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = K;
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = bivar_gauss_angular_bern_model_namespace::bivar_gauss_angular_bern_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return bivar_gauss_angular_bern_model_namespace::profiles__;
}
#endif