---
title: "tables for prelim"
author: "Liz Lawler"
date: "`r Sys.Date()`"
output: 
  pdf_document: 
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(tidyverse)
```



```{r}
c("gauss", "logistic", "inv_log", "asym_log", "dirichlet", "rectangular") 
ind_mid_wts <- readRDS("~/Desktop/research/gaugeDependence/stacking_weights/ind_mid_wts.RDS")
one_set <- ind_mid_wts[[40]] |> unlist() |> 
  as.data.frame() |> 
  rownames_to_column() |> 
  as_tibble() |>
  rename("wts_model" = rowname, "weights" = "unlist(ind_mid_wts[[40]])") |>
  separate_wider_delim(cols = "wts_model", delim = ".", names = c("method", "model")) |>
  mutate(model = case_when(model == 'model1' ~ 'Gaussian',
                           model == 'model2' ~ 'Logistic',
                           model == 'model3' ~ 'Inv. logistic',
                           model == 'model4' ~ 'Asym. logistic',
                           model == 'model5' ~ 'Dirichlet',
                           model == 'model6' ~ 'Rectangular')) |>
  pivot_wider(names_from = method, values_from = weights) |>
  rename('Gauge function' = model, 'Stacking' = stacking, 'Pseudo-BMA+' = pseudobma_boot, 'Pseudo-BMA' = pseudobma_noboot)

one_set |> arrange(-Stacking) |> kbl(format='latex', align = c('l', 'c', 'c', 'c'), booktabs=T, escape = F, digits = 3, 
      caption = "BMA weights for one AI dataset", position = "h!")

dep_mid_wts <- readRDS("~/Desktop/research/gaugeDependence/stacking_weights/dep_mid_wts.RDS")
one_set <- dep_mid_wts[[50]] |> unlist() |> 
  as.data.frame() |> 
  rownames_to_column() |> 
  as_tibble() |>
  rename("wts_model" = rowname, "weights" = "unlist(dep_mid_wts[[50]])") |>
  separate_wider_delim(cols = "wts_model", delim = ".", names = c("method", "model")) |>
  mutate(model = case_when(model == 'model1' ~ 'Gaussian',
                           model == 'model2' ~ 'Logistic',
                           model == 'model3' ~ 'Inv. logistic',
                           model == 'model4' ~ 'Asym. logistic',
                           model == 'model5' ~ 'Dirichlet',
                           model == 'model6' ~ 'Rectangular')) |>
  pivot_wider(names_from = method, values_from = weights) |>
  rename('Gauge function' = model, 'Stacking' = stacking, 'Pseudo-BMA+' = pseudobma_boot, 'Pseudo-BMA' = pseudobma_noboot)

one_set |> arrange(-Stacking) |> kbl(format='latex', align = c('l', 'c', 'c', 'c'), booktabs=T, escape = F, digits = 3, 
      caption = "BMA weights for one AD dataset", position = "h!")
```

