
// Code generated by stanc v2.31.0
#include <stan/model/model_header.hpp>
namespace bivar_trunc_dirichlet_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 67> locations_array__ = 
{" (found before start of program)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 28, column 2 to column 22)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 29, column 2 to column 23)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 30, column 2 to column 23)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 34, column 2 to column 18)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 38, column 4 to column 58)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 36, column 18 to line 39, column 3)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 36, column 2 to line 39, column 3)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 54, column 2 to column 21)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 58, column 4 to column 78)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 56, column 18 to line 59, column 3)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 56, column 2 to line 59, column 3)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 43, column 2 to column 22)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 44, column 2 to column 30)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 45, column 2 to column 30)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 49, column 4 to column 75)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 47, column 18 to line 50, column 3)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 47, column 2 to line 50, column 3)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 7, column 2 to column 17)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 8, column 8 to column 9)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 8, column 2 to column 27)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 9, column 8 to column 9)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 9, column 2 to column 36)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 10, column 2 to column 18)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 11, column 8 to column 9)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 11, column 2 to column 30)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 12, column 8 to column 10)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 12, column 2 to column 29)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 19, column 8 to column 10)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 19, column 2 to column 43)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 20, column 8 to column 10)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 20, column 2 to column 52)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 21, column 8 to column 10)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 21, column 2 to column 49)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 34, column 9 to column 11)",
 " (in 'stan/bivar_trunc_dirichlet.stan', line 54, column 9 to column 11)",
 " (in 'stan//gauge_fcns.stanfunctions', line 3, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 4, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 2, column 38, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 9, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 10, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 11, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 8, column 41, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 16, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 17, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 18, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 15, column 40, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 23, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 24, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 25, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 22, column 41, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 30, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 31, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 29, column 58, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 36, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 37, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//gauge_fcns.stanfunctions', line 35, column 44, included from\n'stan/bivar_trunc_dirichlet.stan', line 2, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 3, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 4, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 5, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 2, column 66, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 13, column 6, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 12, column 11, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 11, column 6, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 10, column 23, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 10, column 4, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)",
 " (in 'stan//likelihoodGamma.stanfunctions', line 9, column 70, included from\n'stan/bivar_trunc_dirichlet.stan', line 3, column 2)"};

struct rectangular_gauge_functor__ {
  template <typename T0__, typename T1__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  operator()(const T0__& w1, const T1__& dep, std::ostream* pstream__) const;
};
struct dirichlet_gauge_functor__ {
  template <typename T0__, typename T1__, typename T2__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__>
  operator()(const T0__& w1, const T1__& theta1, const T2__& theta2,
             std::ostream* pstream__) const;
};
struct asym_log_gauge_functor__ {
  template <typename T0__, typename T1__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  operator()(const T0__& w1, const T1__& dep, std::ostream* pstream__) const;
};
struct cens_gamma_lpdf_functor__ {
  template <bool propto__, typename T0__, typename T1__, typename T2__,
            typename T3__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  operator()(const T0__& y, const T1__& threshold, const T2__& alpha,
             const T3__& beta, std::ostream* pstream__) const;
};
struct inv_log_gauge_functor__ {
  template <typename T0__, typename T1__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  operator()(const T0__& w1, const T1__& dep, std::ostream* pstream__) const;
};
struct logistic_gauge_functor__ {
  template <typename T0__, typename T1__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  operator()(const T0__& w1, const T1__& dep, std::ostream* pstream__) const;
};
struct trunc_gamma_lpdf_functor__ {
  template <bool propto__, typename T0__, typename T1__, typename T2__,
            typename T3__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>,
                                stan::is_stan_scalar<T2__>,
                                stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  operator()(const T0__& y, const T1__& ymin, const T2__& alpha,
             const T3__& beta, std::ostream* pstream__) const;
};
struct gauss_gauge_functor__ {
  template <typename T0__, typename T1__,
            stan::require_all_t<stan::is_stan_scalar<T0__>,
                                stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  operator()(const T0__& w1, const T1__& rho, std::ostream* pstream__) const;
};

template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  gauss_gauge(const T0__& w1, const T1__& rho, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ w2 = DUMMY_VAR__;
      current_statement__ = 36;
      w2 = (1 - w1);
      current_statement__ = 37;
      return (((w1 + w2) - ((2 * rho) * stan::math::sqrt((w1 * w2)))) /
               (1 - stan::math::pow(rho, 2)));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  logistic_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ w2 = DUMMY_VAR__;
      current_statement__ = 39;
      w2 = (1 - w1);
      local_scalar_t__ dep_inv = DUMMY_VAR__;
      current_statement__ = 40;
      dep_inv = (1 / dep);
      current_statement__ = 41;
      return ((dep_inv * stan::math::fmax(w1, w2)) +
               ((1 - dep_inv) * stan::math::fmin(w1, w2)));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  inv_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ w2 = DUMMY_VAR__;
      current_statement__ = 43;
      w2 = (1 - w1);
      local_scalar_t__ dep_inv = DUMMY_VAR__;
      current_statement__ = 44;
      dep_inv = (1 / dep);
      current_statement__ = 45;
      return stan::math::pow(
               (stan::math::pow(w1, dep_inv) + stan::math::pow(w2, dep_inv)),
               dep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  asym_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ w2 = DUMMY_VAR__;
      current_statement__ = 47;
      w2 = (1 - w1);
      local_scalar_t__ dep_inv = DUMMY_VAR__;
      current_statement__ = 48;
      dep_inv = (1 / dep);
      current_statement__ = 49;
      return stan::math::fmin((w1 + w2),
               ((dep_inv * stan::math::fmax(w1, w2)) +
                 ((1 - dep_inv) * stan::math::fmin(w1, w2))));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__>
  dirichlet_gauge(const T0__& w1, const T1__& theta1, const T2__& theta2,
                  std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ w2 = DUMMY_VAR__;
      current_statement__ = 51;
      w2 = (1 - w1);
      current_statement__ = 52;
      return (((((1 + theta1) + theta2) * stan::math::fmax(w1, w2)) -
                (theta1 * w1)) - (theta2 * w2));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>* = nullptr>
  stan::promote_args_t<T0__, T1__>
  rectangular_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
    int current_statement__ = 0; 
    static constexpr bool propto__ = true;
    (void) propto__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ w2 = DUMMY_VAR__;
      current_statement__ = 54;
      w2 = (1 - w1);
      current_statement__ = 55;
      return stan::math::fmax(
               stan::math::fmax(((w1 - w2) / dep), ((w2 - w1) / dep)),
               ((w1 + w2) / (2 - dep)));
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  trunc_gamma_lpdf(const T0__& y, const T1__& ymin, const T2__& alpha,
                   const T3__& beta, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      local_scalar_t__ lpdf = DUMMY_VAR__;
      current_statement__ = 57;
      lpdf = stan::math::gamma_lpdf<false>(y, alpha, beta);
      local_scalar_t__ cst = DUMMY_VAR__;
      current_statement__ = 58;
      cst = stan::math::gamma_lccdf(ymin, alpha, beta);
      current_statement__ = 59;
      return (lpdf - cst);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
  stan::promote_args_t<T0__, T1__, T2__, T3__>
  cens_gamma_lpdf(const T0__& y, const T1__& threshold, const T2__& alpha,
                  const T3__& beta, std::ostream* pstream__) {
    using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
    int current_statement__ = 0; 
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      current_statement__ = 65;
      if (stan::math::logical_lt(y, threshold)) {
        current_statement__ = 63;
        return stan::math::gamma_lcdf(threshold, alpha, beta);
      } else {
        current_statement__ = 61;
        return stan::math::gamma_lpdf<false>(y, alpha, beta);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    }
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>*>
stan::promote_args_t<T0__, T1__>
rectangular_gauge_functor__::operator()(const T0__& w1, const T1__& dep,
                                        std::ostream* pstream__)  const
{
  return rectangular_gauge(w1, dep, pstream__);
}

template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>>*>
stan::promote_args_t<T0__, T1__, T2__>
dirichlet_gauge_functor__::operator()(const T0__& w1, const T1__& theta1,
                                      const T2__& theta2,
                                      std::ostream* pstream__)  const
{
  return dirichlet_gauge(w1, theta1, theta2, pstream__);
}

template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>*>
stan::promote_args_t<T0__, T1__>
asym_log_gauge_functor__::operator()(const T0__& w1, const T1__& dep,
                                     std::ostream* pstream__)  const
{
  return asym_log_gauge(w1, dep, pstream__);
}

template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
cens_gamma_lpdf_functor__::operator()(const T0__& y, const T1__& threshold,
                                      const T2__& alpha, const T3__& beta,
                                      std::ostream* pstream__)  const
{
  return cens_gamma_lpdf<propto__>(y, threshold, alpha, beta, pstream__);
}

template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>*>
stan::promote_args_t<T0__, T1__>
inv_log_gauge_functor__::operator()(const T0__& w1, const T1__& dep,
                                    std::ostream* pstream__)  const
{
  return inv_log_gauge(w1, dep, pstream__);
}

template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>*>
stan::promote_args_t<T0__, T1__>
logistic_gauge_functor__::operator()(const T0__& w1, const T1__& dep,
                                     std::ostream* pstream__)  const
{
  return logistic_gauge(w1, dep, pstream__);
}

template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
trunc_gamma_lpdf_functor__::operator()(const T0__& y, const T1__& ymin,
                                       const T2__& alpha, const T3__& beta,
                                       std::ostream* pstream__)  const
{
  return trunc_gamma_lpdf<propto__>(y, ymin, alpha, beta, pstream__);
}

template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_stan_scalar<T1__>>*>
stan::promote_args_t<T0__, T1__>
gauss_gauge_functor__::operator()(const T0__& w1, const T1__& rho,
                                  std::ostream* pstream__)  const
{
  return gauss_gauge(w1, rho, pstream__);
}


class bivar_trunc_dirichlet_model final : public model_base_crtp<bivar_trunc_dirichlet_model> {

 private:
  int N;
  std::vector<double> R;
  std::vector<double> W;
  int n0;
  std::vector<double> r0_w;
  std::vector<int> idx;
  std::vector<double> R_trunc;
  std::vector<double> W_trunc;
  std::vector<double> r0_w_trunc; 
  
 
 public:
  ~bivar_trunc_dirichlet_model() { }
  
  inline std::string model_name() const final { return "bivar_trunc_dirichlet_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.31.0", "stancflags = --include-paths=stan/"};
  }
  
  
  bivar_trunc_dirichlet_model(stan::io::var_context& context__,
                              unsigned int random_seed__ = 0,
                              std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "bivar_trunc_dirichlet_model_namespace::bivar_trunc_dirichlet_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 18;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 18;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("R", "N", N);
      current_statement__ = 20;
      context__.validate_dims("data initialization","R","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      R = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 20;
      R = context__.vals_r("R");
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "R", R, 0);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("W", "N", N);
      current_statement__ = 22;
      context__.validate_dims("data initialization","W","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      W = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 22;
      W = context__.vals_r("W");
      current_statement__ = 22;
      stan::math::check_greater_or_equal(function__, "W", W, 0);
      current_statement__ = 22;
      stan::math::check_less_or_equal(function__, "W", W, 1);
      current_statement__ = 23;
      context__.validate_dims("data initialization","n0","int",
           std::vector<size_t>{});
      n0 = std::numeric_limits<int>::min();
      
      
      current_statement__ = 23;
      n0 = context__.vals_i("n0")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "n0", n0, 1);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("r0_w", "N", N);
      current_statement__ = 25;
      context__.validate_dims("data initialization","r0_w","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      r0_w = 
        std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 25;
      r0_w = context__.vals_r("r0_w");
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "r0_w", r0_w, 0);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("idx", "n0", n0);
      current_statement__ = 27;
      context__.validate_dims("data initialization","idx","int",
           std::vector<size_t>{static_cast<size_t>(n0)});
      idx = std::vector<int>(n0, std::numeric_limits<int>::min());
      
      
      current_statement__ = 27;
      idx = context__.vals_i("idx");
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "idx", idx, 1);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("R_trunc", "n0", n0);
      current_statement__ = 29;
      R_trunc = 
        std::vector<double>(n0, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 29;
      stan::model::assign(R_trunc,
        stan::model::rvalue(R, "R", stan::model::index_multi(idx)),
        "assigning variable R_trunc");
      current_statement__ = 30;
      stan::math::validate_non_negative_index("W_trunc", "n0", n0);
      current_statement__ = 31;
      W_trunc = 
        std::vector<double>(n0, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 31;
      stan::model::assign(W_trunc,
        stan::model::rvalue(W, "W", stan::model::index_multi(idx)),
        "assigning variable W_trunc");
      current_statement__ = 32;
      stan::math::validate_non_negative_index("r0_w_trunc", "n0", n0);
      current_statement__ = 33;
      r0_w_trunc = 
        std::vector<double>(n0, std::numeric_limits<double>::quiet_NaN());
      
      
      current_statement__ = 33;
      stan::model::assign(r0_w_trunc,
        stan::model::rvalue(r0_w, "r0_w", stan::model::index_multi(idx)),
        "assigning variable r0_w_trunc");
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "R_trunc", R_trunc, 0);
      current_statement__ = 31;
      stan::math::check_greater_or_equal(function__, "W_trunc", W_trunc, 0);
      current_statement__ = 31;
      stan::math::check_less_or_equal(function__, "W_trunc", W_trunc, 1);
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "r0_w_trunc",
                                            r0_w_trunc, 0);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("beta", "n0", n0);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("log_lik", "n0", n0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "bivar_trunc_dirichlet_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      local_scalar_t__ theta1 = DUMMY_VAR__;
      current_statement__ = 2;
      theta1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      local_scalar_t__ theta2 = DUMMY_VAR__;
      current_statement__ = 3;
      theta2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      Eigen::Matrix<local_scalar_t__, -1, 1> beta =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(n0, DUMMY_VAR__);
      current_statement__ = 7;
      for (int n = 1; n <= n0; ++n) {
        current_statement__ = 5;
        stan::model::assign(beta,
          dirichlet_gauge(
            stan::model::rvalue(W_trunc, "W_trunc",
              stan::model::index_uni(n)), theta1, theta2, pstream__),
          "assigning variable beta", stan::model::index_uni(n));
      }
      {
        current_statement__ = 12;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, 4, 2));
        current_statement__ = 13;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(theta1, 4, 0, 4));
        current_statement__ = 14;
        lp_accum__.add(stan::math::student_t_lpdf<propto__>(theta2, 4, 0, 2));
        current_statement__ = 17;
        for (int n = 1; n <= n0; ++n) {
          current_statement__ = 15;
          lp_accum__.add(
            trunc_gamma_lpdf<false>(
              stan::model::rvalue(R_trunc, "R_trunc",
                stan::model::index_uni(n)),
              stan::model::rvalue(r0_w_trunc, "r0_w_trunc",
                stan::model::index_uni(n)), alpha,
              stan::model::rvalue(beta, "beta", stan::model::index_uni(n)), pstream__));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "bivar_trunc_dirichlet_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      double theta1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      theta1 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      double theta2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      theta2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      Eigen::Matrix<double, -1, 1> beta =
         Eigen::Matrix<double, -1, 1>::Constant(n0,
           std::numeric_limits<double>::quiet_NaN());
      out__.write(alpha);
      out__.write(theta1);
      out__.write(theta2);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      for (int n = 1; n <= n0; ++n) {
        current_statement__ = 5;
        stan::model::assign(beta,
          dirichlet_gauge(
            stan::model::rvalue(W_trunc, "W_trunc",
              stan::model::index_uni(n)), theta1, theta2, pstream__),
          "assigning variable beta", stan::model::index_uni(n));
      }
      if (emit_transformed_parameters__) {
        out__.write(beta);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> log_lik =
         Eigen::Matrix<double, -1, 1>::Constant(n0,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 11;
      for (int n = 1; n <= n0; ++n) {
        current_statement__ = 9;
        stan::model::assign(log_lik,
          trunc_gamma_lpdf<false>(
            stan::model::rvalue(R_trunc, "R_trunc",
              stan::model::index_uni(n)),
            stan::model::rvalue(r0_w_trunc, "r0_w_trunc",
              stan::model::index_uni(n)), alpha,
            stan::model::rvalue(beta, "beta", stan::model::index_uni(n)), pstream__),
          "assigning variable log_lik", stan::model::index_uni(n));
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ alpha = DUMMY_VAR__;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      local_scalar_t__ theta1 = DUMMY_VAR__;
      theta1 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, theta1);
      local_scalar_t__ theta2 = DUMMY_VAR__;
      theta2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, theta2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"alpha", "theta1", "theta2", "beta",
      "log_lik"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(n0)},
      std::vector<size_t>{static_cast<size_t>(n0)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "theta1");
    param_names__.emplace_back(std::string() + "theta2");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n0; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n0; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "theta1");
    param_names__.emplace_back(std::string() + "theta2");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= n0; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n0; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n0) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n0) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n0) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n0) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((1 + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * n0;
      const size_t num_gen_quantities = emit_generated_quantities * n0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((1 + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * n0;
      const size_t num_gen_quantities = emit_generated_quantities * n0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 3> names__{"alpha", "theta1",
      "theta2"};
      const std::array<Eigen::Index, 3> constrain_param_sizes__{1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
     }; } 
using stan_model = bivar_trunc_dirichlet_model_namespace::bivar_trunc_dirichlet_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return bivar_trunc_dirichlet_model_namespace::profiles__;
}

#endif


