// Code generated by stanc v2.34.0
#include <stan/model/model_header.hpp>
namespace bivar_trunc_gamma_inv_log_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 44> locations_array__ =
  {" (found before start of program)",
  " (in 'stan//data_params.stan', line 10, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 5, column 0)",
  " (in 'stan//data_params.stan', line 11, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 5, column 0)",
  " (in 'stan/bivar_trunc_gamma_inv_log.stan', line 7, column 2 to column 17)",
  " (in 'stan//model_gq.stan', line 12, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan/bivar_trunc_gamma_inv_log.stan', line 9, column 4 to column 39)",
  " (in 'stan/bivar_trunc_gamma_inv_log.stan', line 8, column 17 to line 10, column 3)",
  " (in 'stan/bivar_trunc_gamma_inv_log.stan', line 8, column 2 to line 10, column 3)",
  " (in 'stan//model_gq.stan', line 14, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan//model_gq.stan', line 13, column 17, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan//model_gq.stan', line 13, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan//model_gq.stan', line 3, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan//model_gq.stan', line 4, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan//model_gq.stan', line 7, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan//model_gq.stan', line 6, column 17, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan//model_gq.stan', line 6, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan//data_params.stan', line 3, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 5, column 0)",
  " (in 'stan//data_params.stan', line 4, column 9, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 5, column 0)",
  " (in 'stan//data_params.stan', line 4, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 5, column 0)",
  " (in 'stan//data_params.stan', line 5, column 9, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 5, column 0)",
  " (in 'stan//data_params.stan', line 5, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 5, column 0)",
  " (in 'stan//data_params.stan', line 6, column 9, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 5, column 0)",
  " (in 'stan//data_params.stan', line 6, column 2, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 5, column 0)",
  " (in 'stan/bivar_trunc_gamma_inv_log.stan', line 7, column 9 to column 10)",
  " (in 'stan//model_gq.stan', line 12, column 9, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 12, column 0)",
  " (in 'stan//gauge_fcns.stanfunctions', line 3, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 4, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 2, column 38, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 9, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 10, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 11, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 8, column 41, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 16, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 17, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 18, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 15, column 40, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 23, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 24, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 25, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//gauge_fcns.stanfunctions', line 22, column 41, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 2, column 2)",
  " (in 'stan//truncGamma.stanfunctions', line 3, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 3, column 2)",
  " (in 'stan//truncGamma.stanfunctions', line 4, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 3, column 2)",
  " (in 'stan//truncGamma.stanfunctions', line 5, column 4, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 3, column 2)",
  " (in 'stan//truncGamma.stanfunctions', line 2, column 66, included from\n'stan/bivar_trunc_gamma_inv_log.stan', line 3, column 2)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
gauss_gauge(const T0__& w1, const T1__& rho, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
logistic_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
inv_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
asym_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
trunc_gamma_lpdf(const T0__& y, const T1__& ymin, const T2__& alpha,
                 const T3__& beta, std::ostream* pstream__);
// real gauss_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
gauss_gauge(const T0__& w1, const T1__& rho, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 25;
    w2 = (1 - w1);
    current_statement__ = 26;
    return (((w1 + w2) - ((2 * rho) * stan::math::sqrt((w1 * w2)))) / (1 -
           stan::math::pow(rho, 2)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real logistic_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
logistic_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 28;
    w2 = (1 - w1);
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 29;
    dep_inv = (1 / dep);
    current_statement__ = 30;
    return ((dep_inv * stan::math::fmax(w1, w2)) + ((1 - dep_inv) *
           stan::math::fmin(w1, w2)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real inv_log_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
inv_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 32;
    w2 = (1 - w1);
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 33;
    dep_inv = (1 / dep);
    current_statement__ = 34;
    return stan::math::pow((stan::math::pow(w1, dep_inv) +
             stan::math::pow(w2, dep_inv)), dep);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real asym_log_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
asym_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 36;
    w2 = (1 - w1);
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 37;
    dep_inv = (1 / dep);
    current_statement__ = 38;
    return stan::math::fmin((w1 + w2), ((dep_inv * stan::math::fmax(w1, w2))
             + ((1 - dep_inv) * stan::math::fmin(w1, w2))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real trunc_gamma_lpdf(real, real, real, real)
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
trunc_gamma_lpdf(const T0__& y, const T1__& ymin, const T2__& alpha,
                 const T3__& beta, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ lpdf = DUMMY_VAR__;
    current_statement__ = 40;
    lpdf = stan::math::gamma_lpdf<false>(y, alpha, beta);
    local_scalar_t__ cst = DUMMY_VAR__;
    current_statement__ = 41;
    cst = stan::math::gamma_lccdf(ymin, alpha, beta);
    current_statement__ = 42;
    return (lpdf - cst);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class bivar_trunc_gamma_inv_log_model final : public model_base_crtp<bivar_trunc_gamma_inv_log_model> {
 private:
  int N;
  Eigen::Matrix<double,-1,1> R_data__;
  Eigen::Matrix<double,-1,1> W_data__;
  Eigen::Matrix<double,-1,1> r0_w_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> R{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> W{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> r0_w{nullptr, 0};
 public:
  ~bivar_trunc_gamma_inv_log_model() {}
  bivar_trunc_gamma_inv_log_model(stan::io::var_context& context__,
                                  unsigned int random_seed__ = 0,
                                  std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "bivar_trunc_gamma_inv_log_model_namespace::bivar_trunc_gamma_inv_log_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 16;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 16;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 17;
      stan::math::validate_non_negative_index("R", "N", N);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "R", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      R_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&R) Eigen::Map<Eigen::Matrix<double,-1,1>>(R_data__.data(), N);
      {
        std::vector<local_scalar_t__> R_flat__;
        current_statement__ = 18;
        R_flat__ = context__.vals_r("R");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(R, R_flat__[(pos__ - 1)],
            "assigning variable R", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      stan::math::validate_non_negative_index("W", "N", N);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      W_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&W) Eigen::Map<Eigen::Matrix<double,-1,1>>(W_data__.data(), N);
      {
        std::vector<local_scalar_t__> W_flat__;
        current_statement__ = 20;
        W_flat__ = context__.vals_r("W");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(W, W_flat__[(pos__ - 1)],
            "assigning variable W", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      stan::math::validate_non_negative_index("r0_w", "N", N);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "r0_w", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      r0_w_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                      std::numeric_limits<double>::quiet_NaN());
      new (&r0_w) Eigen::Map<Eigen::Matrix<double,-1,1>>(r0_w_data__.data(),
        N);
      {
        std::vector<local_scalar_t__> r0_w_flat__;
        current_statement__ = 22;
        r0_w_flat__ = context__.vals_r("r0_w");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(r0_w, r0_w_flat__[(pos__ - 1)],
            "assigning variable r0_w", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 23;
      stan::math::validate_non_negative_index("beta", "N", N);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1;
  }
  inline std::string model_name() const final {
    return "bivar_trunc_gamma_inv_log_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.34.0",
             "stancflags = --include-paths=stan/"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_trunc_gamma_inv_log_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 2;
      dep = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 7;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 5;
        stan::model::assign(beta,
          inv_log_gauge(
            stan::model::rvalue(W, "W", stan::model::index_uni(n)), dep,
            pstream__), "assigning variable beta", stan::model::index_uni(n));
      }
      {
        current_statement__ = 11;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, 2, 4));
        current_statement__ = 12;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(dep, 1.5, 1.5));
        current_statement__ = 15;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 13;
          lp_accum__.add(trunc_gamma_lpdf<false>(
                           stan::model::rvalue(R, "R",
                             stan::model::index_uni(n)),
                           stan::model::rvalue(r0_w, "r0_w",
                             stan::model::index_uni(n)), alpha,
                           stan::model::rvalue(beta, "beta",
                             stan::model::index_uni(n)), pstream__));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_trunc_gamma_inv_log_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 2;
      dep = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 7;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 5;
        stan::model::assign(beta,
          inv_log_gauge(
            stan::model::rvalue(W, "W", stan::model::index_uni(n)), dep,
            pstream__), "assigning variable beta", stan::model::index_uni(n));
      }
      {
        current_statement__ = 11;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, 2, 4));
        current_statement__ = 12;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(dep, 1.5, 1.5));
        current_statement__ = 15;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 13;
          lp_accum__.add(trunc_gamma_lpdf<false>(
                           stan::model::rvalue(R, "R",
                             stan::model::index_uni(n)),
                           stan::model::rvalue(r0_w, "r0_w",
                             stan::model::index_uni(n)), alpha,
                           stan::model::rvalue(beta, "beta",
                             stan::model::index_uni(n)), pstream__));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "bivar_trunc_gamma_inv_log_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double dep = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      dep = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(alpha);
      out__.write(dep);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 7;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 5;
        stan::model::assign(beta,
          inv_log_gauge(
            stan::model::rvalue(W, "W", stan::model::index_uni(n)), dep,
            pstream__), "assigning variable beta", stan::model::index_uni(n));
      }
      if (emit_transformed_parameters__) {
        out__.write(beta);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 10;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 8;
        stan::model::assign(log_lik,
          trunc_gamma_lpdf<false>(
            stan::model::rvalue(R, "R", stan::model::index_uni(n)),
            stan::model::rvalue(r0_w, "r0_w", stan::model::index_uni(n)),
            alpha,
            stan::model::rvalue(beta, "beta", stan::model::index_uni(n)),
            pstream__), "assigning variable log_lik",
          stan::model::index_uni(n));
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 2;
      dep = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, dep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "dep", "double",
        std::vector<size_t>{});
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      out__.write_free_lb(0, alpha);
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 2;
      dep = context__.vals_r("dep")[(1 - 1)];
      out__.write_free_lub(0, 1, dep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha", "dep"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"beta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "dep");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "dep");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dep\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dep\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (N);
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (N);
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = bivar_trunc_gamma_inv_log_model_namespace::bivar_trunc_gamma_inv_log_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return bivar_trunc_gamma_inv_log_model_namespace::profiles__;
}
#endif