// Code generated by stanc v2.34.0
#include <stan/model/model_header.hpp>
namespace bivar_cens_marg_gauss_mix_betas_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 67> locations_array__ =
  {" (found before start of program)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 19, column 2 to column 22)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 20, column 2 to column 30)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 23, column 2 to column 21)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 24, column 2 to column 33)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 25, column 2 to column 25)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 29, column 2 to column 46)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 30, column 2 to column 49)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 34, column 2 to column 22)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 35, column 2 to column 22)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 36, column 2 to column 20)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 37, column 2 to column 24)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 39, column 9 to column 10)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 39, column 2 to column 39)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 41, column 11 to column 12)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 41, column 4 to column 32)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 43, column 6 to column 66)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 42, column 19 to line 44, column 5)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 42, column 4 to line 44, column 5)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 45, column 4 to column 31)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 46, column 4 to column 77)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 40, column 17 to line 47, column 3)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 40, column 2 to line 47, column 3)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 7, column 2 to column 17)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 8, column 8 to column 9)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 8, column 2 to column 27)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 9, column 8 to column 9)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 9, column 2 to column 36)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 10, column 8 to column 9)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 10, column 2 to column 30)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 14, column 2 to column 21)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 23, column 10 to column 11)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 24, column 27 to column 28)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 25, column 18 to column 19)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 29, column 18 to column 19)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 30, column 18 to column 19)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 3, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 4, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 2, column 38, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 9, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 10, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 11, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 8, column 41, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 16, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 17, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 18, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 15, column 40, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 23, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 24, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 25, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 22, column 41, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 30, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 31, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 29, column 58, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 36, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 37, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 35, column 44, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 2, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 3, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 4, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 5, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 2, column 66, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 13, column 6, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 12, column 11, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 11, column 6, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 10, column 23, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 10, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 9, column 70, included from\n'stan/radial_angular/bivar_cens_marg_gauss_mix_betas.stan', line 3, column 2)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
gauss_gauge(const T0__& w1, const T1__& rho, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
logistic_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
inv_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
asym_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
dirichlet_gauge(const T0__& w1, const T1__& theta1, const T2__& theta2,
                std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
rectangular_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
trunc_gamma_lpdf(const T0__& y, const T1__& ymin, const T2__& alpha,
                 const T3__& beta, std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
cens_gamma_lpdf(const T0__& y, const T1__& threshold, const T2__& alpha,
                const T3__& beta, std::ostream* pstream__);
// real gauss_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
gauss_gauge(const T0__& w1, const T1__& rho, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 36;
    w2 = (1 - w1);
    current_statement__ = 37;
    return (((w1 + w2) - ((2 * rho) * stan::math::sqrt((w1 * w2)))) / (1 -
           stan::math::pow(rho, 2)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real logistic_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
logistic_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 39;
    w2 = (1 - w1);
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 40;
    dep_inv = (1 / dep);
    current_statement__ = 41;
    return ((dep_inv * stan::math::fmax(w1, w2)) + ((1 - dep_inv) *
           stan::math::fmin(w1, w2)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real inv_log_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
inv_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 43;
    w2 = (1 - w1);
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 44;
    dep_inv = (1 / dep);
    current_statement__ = 45;
    return stan::math::pow((stan::math::pow(w1, dep_inv) +
             stan::math::pow(w2, dep_inv)), dep);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real asym_log_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
asym_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 47;
    w2 = (1 - w1);
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 48;
    dep_inv = (1 / dep);
    current_statement__ = 49;
    return stan::math::fmin((w1 + w2), ((dep_inv * stan::math::fmax(w1, w2))
             + ((1 - dep_inv) * stan::math::fmin(w1, w2))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real dirichlet_gauge(real, real, real)
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>*>
stan::promote_args_t<T0__, T1__, T2__>
dirichlet_gauge(const T0__& w1, const T1__& theta1, const T2__& theta2,
                std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 51;
    w2 = (1 - w1);
    current_statement__ = 52;
    return (((((1 + theta1) + theta2) * stan::math::fmax(w1, w2)) - (theta1 *
           w1)) - (theta2 * w2));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real rectangular_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
rectangular_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 54;
    w2 = (1 - w1);
    current_statement__ = 55;
    return stan::math::fmax(
             stan::math::fmax(((w1 - w2) / dep), ((w2 - w1) / dep)), ((w1 +
             w2) / (2 - dep)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real trunc_gamma_lpdf(real, real, real, real)
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
trunc_gamma_lpdf(const T0__& y, const T1__& ymin, const T2__& alpha,
                 const T3__& beta, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ lpdf = DUMMY_VAR__;
    current_statement__ = 57;
    lpdf = stan::math::gamma_lpdf<false>(y, alpha, beta);
    local_scalar_t__ cst = DUMMY_VAR__;
    current_statement__ = 58;
    cst = stan::math::gamma_lccdf(ymin, alpha, beta);
    current_statement__ = 59;
    return (lpdf - cst);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real cens_gamma_lpdf(real, real, real, real)
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
cens_gamma_lpdf(const T0__& y, const T1__& threshold, const T2__& alpha,
                const T3__& beta, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 65;
    if (stan::math::logical_lt(y, threshold)) {
      current_statement__ = 63;
      return stan::math::gamma_lcdf(threshold, alpha, beta);
    } else {
      current_statement__ = 61;
      return stan::math::gamma_lpdf<false>(y, alpha, beta);
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class bivar_cens_marg_gauss_mix_betas_model final : public model_base_crtp<bivar_cens_marg_gauss_mix_betas_model> {
 private:
  int N;
  std::vector<double> R;
  std::vector<double> W;
  std::vector<double> r0_w;
  int K;
 public:
  ~bivar_cens_marg_gauss_mix_betas_model() {}
  bivar_cens_marg_gauss_mix_betas_model(stan::io::var_context& context__,
                                        unsigned int random_seed__ = 0,
                                        std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "bivar_cens_marg_gauss_mix_betas_model_namespace::bivar_cens_marg_gauss_mix_betas_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 23;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 23;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("R", "N", N);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "R", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      R = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 25;
      R = context__.vals_r("R");
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "R", R, 0);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("W", "N", N);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      W = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 27;
      W = context__.vals_r("W");
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "W", W, 0);
      current_statement__ = 27;
      stan::math::check_less_or_equal(function__, "W", W, 1);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("r0_w", "N", N);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "r0_w", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      r0_w = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 29;
      r0_w = context__.vals_r("r0_w");
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "r0_w", r0_w, 0);
      current_statement__ = 30;
      K = std::numeric_limits<int>::min();
      current_statement__ = 30;
      K = 3;
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 31;
      stan::math::validate_positive_index("weights", "K", K);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("mu", "K", K);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("tau", "K", K);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("alpha_angles", "K", K);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("beta_angles", "K", K);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + (K - 1) + K + K;
  }
  inline std::string model_name() const final {
    return "bivar_cens_marg_gauss_mix_betas_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.34.0",
             "stancflags = --include-paths=stan/radial_angular"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_cens_marg_gauss_mix_betas_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 2;
      dep = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> weights =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      weights = in__.template read_constrain_simplex<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      mu = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, 1, lp__, K);
      Eigen::Matrix<local_scalar_t__,-1,1> tau =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 5;
      tau = in__.template read_constrain_lb<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, K);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_angles =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(alpha_angles, stan::math::elt_multiply(mu, tau),
        "assigning variable alpha_angles");
      Eigen::Matrix<local_scalar_t__,-1,1> beta_angles =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(beta_angles,
        stan::math::elt_multiply(stan::math::subtract(1, mu), tau),
        "assigning variable beta_angles");
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "alpha_angles",
        alpha_angles, 0);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "beta_angles",
        beta_angles, 0);
      {
        current_statement__ = 8;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, 4, 2));
        current_statement__ = 9;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(dep, 0, 1));
        current_statement__ = 10;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(mu, 0, 1));
        current_statement__ = 11;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(tau, 0, 2));
        current_statement__ = 12;
        stan::math::validate_non_negative_index("log_weights", "K", K);
        Eigen::Matrix<local_scalar_t__,-1,1> log_weights =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
        current_statement__ = 13;
        stan::model::assign(log_weights, stan::math::log(weights),
          "assigning variable log_weights");
        current_statement__ = 22;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 14;
          stan::math::validate_non_negative_index("lps", "K", K);
          Eigen::Matrix<local_scalar_t__,-1,1> lps =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
          current_statement__ = 15;
          stan::model::assign(lps, log_weights, "assigning variable lps");
          current_statement__ = 18;
          for (int j = 1; j <= K; ++j) {
            current_statement__ = 16;
            stan::model::assign(lps,
              (stan::model::rvalue(lps, "lps", stan::model::index_uni(j)) +
              stan::math::beta_lpdf<false>(
                stan::model::rvalue(W, "W", stan::model::index_uni(n)),
                stan::model::rvalue(alpha_angles, "alpha_angles",
                  stan::model::index_uni(j)),
                stan::model::rvalue(beta_angles, "beta_angles",
                  stan::model::index_uni(j)))), "assigning variable lps",
              stan::model::index_uni(j));
          }
          current_statement__ = 19;
          lp_accum__.add(stan::math::log_sum_exp(lps));
          current_statement__ = 20;
          lp_accum__.add(cens_gamma_lpdf<false>(
                           stan::model::rvalue(R, "R",
                             stan::model::index_uni(n)),
                           stan::model::rvalue(r0_w, "r0_w",
                             stan::model::index_uni(n)), alpha,
                           gauss_gauge(
                             stan::model::rvalue(W, "W",
                               stan::model::index_uni(n)), dep, pstream__),
                           pstream__));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_cens_marg_gauss_mix_betas_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 2;
      dep = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> weights =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      weights = in__.template read_constrain_simplex<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      mu = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, 1, lp__, K);
      Eigen::Matrix<local_scalar_t__,-1,1> tau =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 5;
      tau = in__.template read_constrain_lb<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, K);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_angles =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(alpha_angles, stan::math::elt_multiply(mu, tau),
        "assigning variable alpha_angles");
      Eigen::Matrix<local_scalar_t__,-1,1> beta_angles =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(beta_angles,
        stan::math::elt_multiply(stan::math::subtract(1, mu), tau),
        "assigning variable beta_angles");
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "alpha_angles",
        alpha_angles, 0);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "beta_angles",
        beta_angles, 0);
      {
        current_statement__ = 8;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, 4, 2));
        current_statement__ = 9;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(dep, 0, 1));
        current_statement__ = 10;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(mu, 0, 1));
        current_statement__ = 11;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(tau, 0, 2));
        current_statement__ = 12;
        stan::math::validate_non_negative_index("log_weights", "K", K);
        Eigen::Matrix<local_scalar_t__,-1,1> log_weights =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
        current_statement__ = 13;
        stan::model::assign(log_weights, stan::math::log(weights),
          "assigning variable log_weights");
        current_statement__ = 22;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 14;
          stan::math::validate_non_negative_index("lps", "K", K);
          Eigen::Matrix<local_scalar_t__,-1,1> lps =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
          current_statement__ = 15;
          stan::model::assign(lps, log_weights, "assigning variable lps");
          current_statement__ = 18;
          for (int j = 1; j <= K; ++j) {
            current_statement__ = 16;
            stan::model::assign(lps,
              (stan::model::rvalue(lps, "lps", stan::model::index_uni(j)) +
              stan::math::beta_lpdf<false>(
                stan::model::rvalue(W, "W", stan::model::index_uni(n)),
                stan::model::rvalue(alpha_angles, "alpha_angles",
                  stan::model::index_uni(j)),
                stan::model::rvalue(beta_angles, "beta_angles",
                  stan::model::index_uni(j)))), "assigning variable lps",
              stan::model::index_uni(j));
          }
          current_statement__ = 19;
          lp_accum__.add(stan::math::log_sum_exp(lps));
          current_statement__ = 20;
          lp_accum__.add(cens_gamma_lpdf<false>(
                           stan::model::rvalue(R, "R",
                             stan::model::index_uni(n)),
                           stan::model::rvalue(r0_w, "r0_w",
                             stan::model::index_uni(n)), alpha,
                           gauss_gauge(
                             stan::model::rvalue(W, "W",
                               stan::model::index_uni(n)), dep, pstream__),
                           pstream__));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "bivar_cens_marg_gauss_mix_betas_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double dep = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      dep = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<double,-1,1> weights =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      weights = in__.template read_constrain_simplex<
                  Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, K);
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      mu = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, 1, lp__, K);
      Eigen::Matrix<double,-1,1> tau =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      tau = in__.template read_constrain_lb<
              Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, K);
      Eigen::Matrix<double,-1,1> alpha_angles =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> beta_angles =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(alpha);
      out__.write(dep);
      out__.write(weights);
      out__.write(mu);
      out__.write(tau);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 6;
      stan::model::assign(alpha_angles, stan::math::elt_multiply(mu, tau),
        "assigning variable alpha_angles");
      current_statement__ = 7;
      stan::model::assign(beta_angles,
        stan::math::elt_multiply(stan::math::subtract(1, mu), tau),
        "assigning variable beta_angles");
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "alpha_angles",
        alpha_angles, 0);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "beta_angles",
        beta_angles, 0);
      if (emit_transformed_parameters__) {
        out__.write(alpha_angles);
        out__.write(beta_angles);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 2;
      dep = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, dep);
      Eigen::Matrix<local_scalar_t__,-1,1> weights =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(weights,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable weights");
      out__.write_free_simplex(weights);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(mu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable mu");
      out__.write_free_lub(0, 1, mu);
      Eigen::Matrix<local_scalar_t__,-1,1> tau =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(tau,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable tau");
      out__.write_free_lb(0, tau);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "dep", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "weights",
        "double", std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "tau", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      out__.write_free_lb(0, alpha);
      local_scalar_t__ dep = DUMMY_VAR__;
      current_statement__ = 2;
      dep = context__.vals_r("dep")[(1 - 1)];
      out__.write_free_lub(0, 1, dep);
      Eigen::Matrix<local_scalar_t__,-1,1> weights =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> weights_flat__;
        current_statement__ = 3;
        weights_flat__ = context__.vals_r("weights");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          stan::model::assign(weights, weights_flat__[(pos__ - 1)],
            "assigning variable weights", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(weights);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_flat__;
        current_statement__ = 4;
        mu_flat__ = context__.vals_r("mu");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          stan::model::assign(mu, mu_flat__[(pos__ - 1)],
            "assigning variable mu", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lub(0, 1, mu);
      Eigen::Matrix<local_scalar_t__,-1,1> tau =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> tau_flat__;
        current_statement__ = 5;
        tau_flat__ = context__.vals_r("tau");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          stan::model::assign(tau, tau_flat__[(pos__ - 1)],
            "assigning variable tau", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, tau);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha", "dep", "weights", "mu",
                "tau"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"alpha_angles", "beta_angles"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(K)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "dep");
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "weights" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "tau" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "alpha_angles" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta_angles" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "dep");
    for (int sym1__ = 1; sym1__ <= (K - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "weights" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "tau" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "alpha_angles" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta_angles" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dep\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"weights\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"alpha_angles\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_angles\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dep\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"weights\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((K -1)) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"alpha_angles\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta_angles\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((1 + 1) + K) + K) + K);
    const size_t num_transformed = emit_transformed_parameters * ((K + K));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((1 + 1) + K) + K) + K);
    const size_t num_transformed = emit_transformed_parameters * ((K + K));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = bivar_cens_marg_gauss_mix_betas_model_namespace::bivar_cens_marg_gauss_mix_betas_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return bivar_cens_marg_gauss_mix_betas_model_namespace::profiles__;
}
#endif