// Code generated by stanc v2.34.0
#include <stan/model/model_header.hpp>
namespace bivar_cens_marg_gauss_angular_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 71> locations_array__ =
  {" (found before start of program)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 38, column 2 to column 22)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 39, column 2 to column 31)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 40, column 2 to column 31)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 45, column 2 to column 74)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 49, column 2 to column 22)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 50, column 2 to column 23)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 51, column 2 to column 23)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 54, column 4 to column 114)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 53, column 17 to line 55, column 3)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 53, column 2 to line 55, column 3)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 22, column 2 to column 17)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 23, column 8 to column 9)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 23, column 2 to column 27)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 24, column 8 to column 9)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 24, column 2 to column 36)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 25, column 8 to column 9)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 25, column 2 to column 30)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 26, column 2 to column 22)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 27, column 9 to column 15)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 27, column 2 to column 20)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 28, column 9 to column 15)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 28, column 2 to column 20)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 32, column 2 to column 21)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 33, column 9 to column 15)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 33, column 2 to column 37)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 34, column 9 to column 15)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 34, column 2 to column 45)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 3, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 4, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 2, column 38, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 9, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 10, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 11, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 8, column 41, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 16, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 17, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 18, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 15, column 40, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 23, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 24, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 25, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 22, column 41, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 30, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 31, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 29, column 58, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 36, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 37, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/gauge_fcns.stanfunctions', line 35, column 44, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 3, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 3, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 4, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 5, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 2, column 66, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 13, column 6, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 12, column 11, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 11, column 6, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 10, column 23, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 10, column 4, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/likelihoodGamma.stanfunctions', line 9, column 70, included from\n'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 4, column 2)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 7, column 11 to column 16)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 7, column 4 to column 72)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 8, column 11 to column 16)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 8, column 4 to column 35)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 9, column 4 to column 16)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 11, column 5 to column 56)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 10, column 22 to line 12, column 5)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 10, column 4 to line 12, column 5)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 13, column 4 to column 35)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 6, column 72 to line 14, column 3)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 17, column 4 to column 78)",
  " (in 'stan/radial_angular/bivar_cens_marg_gauss_angular.stan', line 16, column 67 to line 18, column 3)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
gauss_gauge(const T0__& w1, const T1__& rho, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
logistic_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
inv_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
asym_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__>
dirichlet_gauge(const T0__& w1, const T1__& theta1, const T2__& theta2,
                std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>* = nullptr>
stan::promote_args_t<T0__, T1__>
rectangular_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
trunc_gamma_lpdf(const T0__& y, const T1__& ymin, const T2__& alpha,
                 const T3__& beta, std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T2__, T3__>
cens_gamma_lpdf(const T0__& y, const T1__& threshold, const T2__& alpha,
                const T3__& beta, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<std::is_integral<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<stan::base_type_t<T1__>, stan::base_type_t<T2__>, T3__>
est_vol(const T0__& n_vol, const T1__& sum_term_arg__, const T2__&
        sqrt_term_arg__, const T3__& pars, std::ostream* pstream__);
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              std::is_integral<T2__>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>* = nullptr>
stan::promote_args_t<T0__, T1__, T3__>
angular_lpdf(const T0__& angle, const T1__& pars, const T2__& dim,
             const T3__& L_volume, std::ostream* pstream__);
// real gauss_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
gauss_gauge(const T0__& w1, const T1__& rho, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 28;
    w2 = (1 - w1);
    current_statement__ = 29;
    return (((w1 + w2) - ((2 * rho) * stan::math::sqrt((w1 * w2)))) / (1 -
           stan::math::pow(rho, 2)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real logistic_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
logistic_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 31;
    w2 = (1 - w1);
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 32;
    dep_inv = (1 / dep);
    current_statement__ = 33;
    return ((dep_inv * stan::math::fmax(w1, w2)) + ((1 - dep_inv) *
           stan::math::fmin(w1, w2)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real inv_log_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
inv_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 35;
    w2 = (1 - w1);
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 36;
    dep_inv = (1 / dep);
    current_statement__ = 37;
    return stan::math::pow((stan::math::pow(w1, dep_inv) +
             stan::math::pow(w2, dep_inv)), dep);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real asym_log_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
asym_log_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 39;
    w2 = (1 - w1);
    local_scalar_t__ dep_inv = DUMMY_VAR__;
    current_statement__ = 40;
    dep_inv = (1 / dep);
    current_statement__ = 41;
    return stan::math::fmin((w1 + w2), ((dep_inv * stan::math::fmax(w1, w2))
             + ((1 - dep_inv) * stan::math::fmin(w1, w2))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real dirichlet_gauge(real, real, real)
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>>*>
stan::promote_args_t<T0__, T1__, T2__>
dirichlet_gauge(const T0__& w1, const T1__& theta1, const T2__& theta2,
                std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 43;
    w2 = (1 - w1);
    current_statement__ = 44;
    return (((((1 + theta1) + theta2) * stan::math::fmax(w1, w2)) - (theta1 *
           w1)) - (theta2 * w2));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real rectangular_gauge(real, real)
template <typename T0__, typename T1__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>>*>
stan::promote_args_t<T0__, T1__>
rectangular_gauge(const T0__& w1, const T1__& dep, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ w2 = DUMMY_VAR__;
    current_statement__ = 46;
    w2 = (1 - w1);
    current_statement__ = 47;
    return stan::math::fmax(
             stan::math::fmax(((w1 - w2) / dep), ((w2 - w1) / dep)), ((w1 +
             w2) / (2 - dep)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real trunc_gamma_lpdf(real, real, real, real)
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
trunc_gamma_lpdf(const T0__& y, const T1__& ymin, const T2__& alpha,
                 const T3__& beta, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ lpdf = DUMMY_VAR__;
    current_statement__ = 49;
    lpdf = stan::math::gamma_lpdf<false>(y, alpha, beta);
    local_scalar_t__ cst = DUMMY_VAR__;
    current_statement__ = 50;
    cst = stan::math::gamma_lccdf(ymin, alpha, beta);
    current_statement__ = 51;
    return (lpdf - cst);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real cens_gamma_lpdf(real, real, real, real)
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              stan::math::disjunction<stan::is_autodiff<T2__>,
                                                      std::is_floating_point<T2__>>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T2__, T3__>
cens_gamma_lpdf(const T0__& y, const T1__& threshold, const T2__& alpha,
                const T3__& beta, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T2__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 57;
    if (stan::math::logical_lt(y, threshold)) {
      current_statement__ = 55;
      return stan::math::gamma_lcdf(threshold, alpha, beta);
    } else {
      current_statement__ = 53;
      return stan::math::gamma_lpdf<false>(y, alpha, beta);
    }
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real est_vol(int, vector, vector, real)
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<std::is_integral<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_col_vector<T2__>,
                              stan::is_vt_not_complex<T2__>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<stan::base_type_t<T1__>, stan::base_type_t<T2__>, T3__>
est_vol(const T0__& n_vol, const T1__& sum_term_arg__, const T2__&
        sqrt_term_arg__, const T3__& pars, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T1__>,
                             stan::base_type_t<T2__>, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  const auto& sum_term = stan::math::to_ref(sum_term_arg__);
  const auto& sqrt_term = stan::math::to_ref(sqrt_term_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 59;
    stan::math::validate_non_negative_index("gx", "n_vol", n_vol);
    Eigen::Matrix<local_scalar_t__,-1,1> gx =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_vol, DUMMY_VAR__);
    current_statement__ = 60;
    stan::model::assign(gx,
      stan::math::divide(
        stan::math::subtract(sum_term,
          stan::math::multiply((2 * pars), sqrt_term)), (1 -
        stan::math::pow(pars, 2))), "assigning variable gx");
    current_statement__ = 61;
    stan::math::validate_non_negative_index("approx_indicator", "n_vol",
      n_vol);
    Eigen::Matrix<local_scalar_t__,-1,1> approx_indicator =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_vol, DUMMY_VAR__);
    local_scalar_t__ k = DUMMY_VAR__;
    current_statement__ = 63;
    k = 15;
    current_statement__ = 66;
    for (int i = 1; i <= n_vol; ++i) {
      current_statement__ = 64;
      stan::model::assign(approx_indicator,
        stan::math::inv_logit((k * (1.0 -
          stan::model::rvalue(gx, "gx", stan::model::index_uni(i))))),
        "assigning variable approx_indicator", stan::model::index_uni(i));
    }
    current_statement__ = 67;
    return stan::math::mean(approx_indicator);
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
// real angular_lpdf(real, real, int, real)
template <bool propto__, typename T0__, typename T1__, typename T2__,
          typename T3__,
          stan::require_all_t<stan::math::disjunction<stan::is_autodiff<T0__>,
                                                      std::is_floating_point<T0__>>,
                              stan::math::disjunction<stan::is_autodiff<T1__>,
                                                      std::is_floating_point<T1__>>,
                              std::is_integral<T2__>,
                              stan::math::disjunction<stan::is_autodiff<T3__>,
                                                      std::is_floating_point<T3__>>>*>
stan::promote_args_t<T0__, T1__, T3__>
angular_lpdf(const T0__& angle, const T1__& pars, const T2__& dim,
             const T3__& L_volume, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__, T1__, T3__>;
  int current_statement__ = 0;
  // suppress unused var warning
  (void) current_statement__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 69;
    return ((-(dim) * stan::math::log(gauss_gauge(angle, pars, pstream__))) -
           (stan::math::log(dim) + stan::math::log(L_volume)));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
class bivar_cens_marg_gauss_angular_model final : public model_base_crtp<bivar_cens_marg_gauss_angular_model> {
 private:
  int N;
  std::vector<double> R;
  std::vector<double> W;
  std::vector<double> r0_w;
  int n_grid;
  Eigen::Matrix<double,-1,1> x1_data__;
  Eigen::Matrix<double,-1,1> x2_data__;
  int d;
  Eigen::Matrix<double,-1,1> sum_x1_x2_data__;
  Eigen::Matrix<double,-1,1> sqrt_x1_x2_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> x1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> x2{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> sum_x1_x2{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> sqrt_x1_x2{nullptr, 0};
 public:
  ~bivar_cens_marg_gauss_angular_model() {}
  bivar_cens_marg_gauss_angular_model(stan::io::var_context& context__,
                                      unsigned int random_seed__ = 0,
                                      std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "bivar_cens_marg_gauss_angular_model_namespace::bivar_cens_marg_gauss_angular_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 11;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 11;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 12;
      stan::math::validate_non_negative_index("R", "N", N);
      current_statement__ = 13;
      context__.validate_dims("data initialization", "R", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      R = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 13;
      R = context__.vals_r("R");
      current_statement__ = 13;
      stan::math::check_greater_or_equal(function__, "R", R, 0);
      current_statement__ = 14;
      stan::math::validate_non_negative_index("W", "N", N);
      current_statement__ = 15;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      W = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 15;
      W = context__.vals_r("W");
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "W", W, 0);
      current_statement__ = 15;
      stan::math::check_less_or_equal(function__, "W", W, 1);
      current_statement__ = 16;
      stan::math::validate_non_negative_index("r0_w", "N", N);
      current_statement__ = 17;
      context__.validate_dims("data initialization", "r0_w", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      r0_w = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 17;
      r0_w = context__.vals_r("r0_w");
      current_statement__ = 17;
      stan::math::check_greater_or_equal(function__, "r0_w", r0_w, 0);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "n_grid", "int",
        std::vector<size_t>{});
      n_grid = std::numeric_limits<int>::min();
      current_statement__ = 18;
      n_grid = context__.vals_i("n_grid")[(1 - 1)];
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "n_grid", n_grid, 1);
      current_statement__ = 19;
      stan::math::validate_non_negative_index("x1", "n_grid", n_grid);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "x1", "double",
        std::vector<size_t>{static_cast<size_t>(n_grid)});
      x1_data__ = Eigen::Matrix<double,-1,1>::Constant(n_grid,
                    std::numeric_limits<double>::quiet_NaN());
      new (&x1) Eigen::Map<Eigen::Matrix<double,-1,1>>(x1_data__.data(),
        n_grid);
      {
        std::vector<local_scalar_t__> x1_flat__;
        current_statement__ = 20;
        x1_flat__ = context__.vals_r("x1");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= n_grid; ++sym1__) {
          stan::model::assign(x1, x1_flat__[(pos__ - 1)],
            "assigning variable x1", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 21;
      stan::math::validate_non_negative_index("x2", "n_grid", n_grid);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "x2", "double",
        std::vector<size_t>{static_cast<size_t>(n_grid)});
      x2_data__ = Eigen::Matrix<double,-1,1>::Constant(n_grid,
                    std::numeric_limits<double>::quiet_NaN());
      new (&x2) Eigen::Map<Eigen::Matrix<double,-1,1>>(x2_data__.data(),
        n_grid);
      {
        std::vector<local_scalar_t__> x2_flat__;
        current_statement__ = 22;
        x2_flat__ = context__.vals_r("x2");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= n_grid; ++sym1__) {
          stan::model::assign(x2, x2_flat__[(pos__ - 1)],
            "assigning variable x2", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 23;
      d = std::numeric_limits<int>::min();
      current_statement__ = 23;
      d = 2;
      current_statement__ = 24;
      stan::math::validate_non_negative_index("sum_x1_x2", "n_grid", n_grid);
      current_statement__ = 25;
      sum_x1_x2_data__ = Eigen::Matrix<double,-1,1>::Constant(n_grid,
                           std::numeric_limits<double>::quiet_NaN());
      new (&sum_x1_x2)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(sum_x1_x2_data__.data(),
        n_grid);
      current_statement__ = 25;
      stan::model::assign(sum_x1_x2, stan::math::add(x1, x2),
        "assigning variable sum_x1_x2");
      current_statement__ = 26;
      stan::math::validate_non_negative_index("sqrt_x1_x2", "n_grid", n_grid);
      current_statement__ = 27;
      sqrt_x1_x2_data__ = Eigen::Matrix<double,-1,1>::Constant(n_grid,
                            std::numeric_limits<double>::quiet_NaN());
      new (&sqrt_x1_x2)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(sqrt_x1_x2_data__.data(),
        n_grid);
      current_statement__ = 27;
      stan::model::assign(sqrt_x1_x2,
        stan::math::sqrt(stan::math::elt_multiply(x1, x2)),
        "assigning variable sqrt_x1_x2");
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "d", d, 1);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "bivar_cens_marg_gauss_angular_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.34.0",
             "stancflags = --include-paths=stan/radial_angular"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_cens_marg_gauss_angular_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ dep1 = DUMMY_VAR__;
      current_statement__ = 2;
      dep1 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      local_scalar_t__ dep2 = DUMMY_VAR__;
      current_statement__ = 3;
      dep2 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      local_scalar_t__ L = DUMMY_VAR__;
      current_statement__ = 4;
      L = est_vol(n_grid, sum_x1_x2, sqrt_x1_x2, dep1, pstream__);
      current_statement__ = 4;
      stan::math::check_greater_or_equal(function__, "L", L, 0);
      current_statement__ = 4;
      stan::math::check_less_or_equal(function__, "L", L, 1);
      {
        current_statement__ = 5;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, 4, 2));
        current_statement__ = 6;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(dep1, 0, 1));
        current_statement__ = 7;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(dep2, 0, 1));
        current_statement__ = 10;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 8;
          lp_accum__.add((angular_lpdf<false>(
                            stan::model::rvalue(W, "W",
                              stan::model::index_uni(n)), dep1, d, L,
                            pstream__) +
            cens_gamma_lpdf<false>(
              stan::model::rvalue(R, "R", stan::model::index_uni(n)),
              stan::model::rvalue(r0_w, "r0_w", stan::model::index_uni(n)),
              alpha,
              gauss_gauge(
                stan::model::rvalue(W, "W", stan::model::index_uni(n)), dep2,
                pstream__), pstream__)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "bivar_cens_marg_gauss_angular_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ dep1 = DUMMY_VAR__;
      current_statement__ = 2;
      dep1 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      local_scalar_t__ dep2 = DUMMY_VAR__;
      current_statement__ = 3;
      dep2 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      local_scalar_t__ L = DUMMY_VAR__;
      current_statement__ = 4;
      L = est_vol(n_grid, sum_x1_x2, sqrt_x1_x2, dep1, pstream__);
      current_statement__ = 4;
      stan::math::check_greater_or_equal(function__, "L", L, 0);
      current_statement__ = 4;
      stan::math::check_less_or_equal(function__, "L", L, 1);
      {
        current_statement__ = 5;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, 4, 2));
        current_statement__ = 6;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(dep1, 0, 1));
        current_statement__ = 7;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(dep2, 0, 1));
        current_statement__ = 10;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 8;
          lp_accum__.add((angular_lpdf<false>(
                            stan::model::rvalue(W, "W",
                              stan::model::index_uni(n)), dep1, d, L,
                            pstream__) +
            cens_gamma_lpdf<false>(
              stan::model::rvalue(R, "R", stan::model::index_uni(n)),
              stan::model::rvalue(r0_w, "r0_w", stan::model::index_uni(n)),
              alpha,
              gauss_gauge(
                stan::model::rvalue(W, "W", stan::model::index_uni(n)), dep2,
                pstream__), pstream__)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "bivar_cens_marg_gauss_angular_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double dep1 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      dep1 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      double dep2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      dep2 = in__.template read_constrain_lub<local_scalar_t__,
               jacobian__>(0, 1, lp__);
      double L = std::numeric_limits<double>::quiet_NaN();
      out__.write(alpha);
      out__.write(dep1);
      out__.write(dep2);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 4;
      L = est_vol(n_grid, sum_x1_x2, sqrt_x1_x2, dep1, pstream__);
      current_statement__ = 4;
      stan::math::check_greater_or_equal(function__, "L", L, 0);
      current_statement__ = 4;
      stan::math::check_less_or_equal(function__, "L", L, 1);
      if (emit_transformed_parameters__) {
        out__.write(L);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      local_scalar_t__ dep1 = DUMMY_VAR__;
      current_statement__ = 2;
      dep1 = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, dep1);
      local_scalar_t__ dep2 = DUMMY_VAR__;
      current_statement__ = 3;
      dep2 = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, dep2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "dep1", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "dep2", "double",
        std::vector<size_t>{});
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      out__.write_free_lb(0, alpha);
      local_scalar_t__ dep1 = DUMMY_VAR__;
      current_statement__ = 2;
      dep1 = context__.vals_r("dep1")[(1 - 1)];
      out__.write_free_lub(0, 1, dep1);
      local_scalar_t__ dep2 = DUMMY_VAR__;
      current_statement__ = 3;
      dep2 = context__.vals_r("dep2")[(1 - 1)];
      out__.write_free_lub(0, 1, dep2);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"alpha", "dep1", "dep2"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"L"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "dep1");
    param_names__.emplace_back(std::string() + "dep2");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "L");
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "dep1");
    param_names__.emplace_back(std::string() + "dep2");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "L");
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dep1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dep2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dep1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"dep2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"L\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((1 + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = bivar_cens_marg_gauss_angular_model_namespace::bivar_cens_marg_gauss_angular_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return bivar_cens_marg_gauss_angular_model_namespace::profiles__;
}
#endif